### ISSUE TITLE
Sorting of camel case morphological features

### ISSUE THREAD

**Issue by jeanm** [Orange-OpenSource/conllueditor#10]
Hi, thanks for this very useful software!

There is an issue with the way the editor is sorting morphological features. It will sort  `NumType` before `Number`, whereas the `validate.py` script from the [UD tools](https://github.com/UniversalDependencies/tools) expects it to be sorted the other way around and will reject it.

**Comment by jheinecke** [comment]
Hi,
I thought that I corrected this a while ago (commit a0351bcc47). But you're right there was a case where features were not correctly ordered (when splitting a token). It should be fine with commit 24068aa (version 2.10.3).

**Comment by jeanm** [comment]
You're absolutely right, I thought I was running on the latest master but I wasn't. Thanks!
