### ISSUE TITLE
MTW => MWT

### ISSUE THREAD

**Issue by martinpopel** [Orange-OpenSource/conllueditor#15]
I believe [the documentation](https://github.com/Orange-OpenSource/conllueditor#commands-to-be-used-with-modify-button) uses a wrong terminology: what is being referred to as **MTW (multi-token word) is actually MWT (multi-word token)**.
See the [official UD documentation](https://universaldependencies.org/u/overview/tokenization.html), which says:

> We refer to such cases as multiword tokens because a single orthographic token corresponds to multiple (syntactic) words.

The MWT name is used in several other projects (e.g. [Udapi](https://github.com/udapi/udapi-python/blob/master/udapi/core/mwt.py)).

It is very misleading for the users because both MWT and MTW are allowed in UD:

> In exceptional cases, it may be necessary to go in the other direction, and combine several orthographic tokens into a single syntactic word. Starting from v2 of the UD guidelines, such multitoken words are allowed for a restricted class of phenomena, such as numerical expressions like 20 000 and abbreviations like e. g., as long as these phenomena are approved and clearly specified in the language-specific documentation.

So a MTW is simply a word whose form (and lemma) includes a space. There is no need for special support of MTW in Conllu editor, I think (except for running the validator and checking that MTWs are used only in the exceptional cases listed for a given language).

**Comment by jheinecke** [comment]
Hi!
You're right. I had started to correct that a while ago but did not finish properly. I'm doing it now and commit as soon as it's done. Thanks for reminding :-)

**Comment by arademaker** [comment]
I thought MTW should be handled with the dependency relation `goeswith`.

**Comment by martinpopel** [comment]
[goeswith](https://universaldependencies.org/u/dep/goeswith.html) is **only** for text that is not well edited, where the extra space is an error, e.g. "with out" or "never the less".

MTW is for expressions like "20 000" and abbreviations like "e. g.", where the space is not an error (although in these two examples some styles/languages allow writing it without the space as well).

This issue is not about real MTW nor goeswith. It is about MWT which were just by a mistake referred to as MTW.

**Comment by jheinecke** [comment]
I corrected the documentation and traces of mtw in the code, so it should be clearer now that we deal with MWT here.
