### ISSUE TITLE
Search for empty nodes?

### ISSUE THREAD

**Issue by francescomambrini** [Orange-OpenSource/conllueditor#16]
I would like to review all the empty nodes in my treebank. According to the help page, it should be possible to use the `Empty` key (no value) in the advanced search field. However, if I try, I get the error: `CoNLL-U error: line 1:0 token recognition error at: 'Em'`.

Am I missing anything? Is there any other way to do this?

Thank you very much for your support!

**Comment by jheinecke** [comment]
Hi, there is indeed a problem, I'll have a look at this, it must have slipped through the tests.

**Comment by jheinecke** [comment]
Fixed ! 
There was something missing (which was not tested). Try
```
git pull
mvn install
```

**Comment by jheinecke** [comment]
I forgot: for the search its `IsEmpty` not just "Empty" (I had to change that a while ago)

**Comment by francescomambrini** [comment]
Thank your for the very quick fix!
Right now I am only able to test with Docker. With `IsEmpty` I no longer get the previous error, but the query returns no results (and I do have a few empty nodes here and there). But the problem might be with the data: I'll have to do some more in-depth testing...

**Comment by jheinecke** [comment]
I didn't push the docker image yet. I'll do it as soon as possible, sorry for that

**Comment by francescomambrini** [comment]
Of course! silly me, I didn't think that the Docker image too needed to be updated... :blush:

**Comment by jheinecke** [comment]
done !

**Comment by francescomambrini** [comment]
It works! (built with mvn and tested)
