### ISSUE TITLE
Docker params

### ISSUE THREAD

**Issue by chiarcos** [Orange-OpenSource/conllueditor#19]
Dear Johannes, thanks for your nice work!
A minor suggestion: You might want to omit `-d` from the docker call (or describe what it does), because otherwise people won't get out error logs ;)

Otherwise, your error logs are helpful, thanks for that. I just got a `head id must be different from word id in line (52)`.

**Comment by jheinecke** [comment]
Hi Christian,
thanks for the feedback. I added a simple explanation on  the`-d` option.
