### ISSUE TITLE
Text comes outside the boxes

### ISSUE THREAD

**Issue by ftyers** [Orange-OpenSource/conllueditor#2]
![Captura de 2020-05-04 13-45-31](https://user-images.githubusercontent.com/449545/80967018-942e4200-8e0d-11ea-807c-32ba99f1bf9a.png)

Could this be fixed somehow? :)

**Comment by JPJPJPOPOP** [comment]
@ftyers You can adjust the width of the tokens in the settings to make them wider, but they don't seem to be able to automatically scale to size.

**Comment by ftyers** [comment]
> @ftyers You can adjust the width of the tokens in the settings to make them wider, but they don't seem to be able to automatically scale to size.

Automatically scaling would be ideal.

**Comment by jheinecke** [comment]
@ftyers I'll try to fix that. In the tree mode words do not overlap that easy

**Comment by jheinecke** [comment]
Hi @ftyers, is this what you need ?
![chukchi](https://user-images.githubusercontent.com/26959109/81584560-2d7fca00-93b3-11ea-9d03-91a5e51f0fe9.png)


I can `git push` it these days. There is still an issue if features or misc is wider than the word, but you can have it know and I'll repair the issue later.

**Comment by jheinecke** [comment]
it's done. Check v2.4.2!
