### ISSUE TITLE
docker: invalid reference format

### ISSUE THREAD

**Issue by Bachstelze** [Orange-OpenSource/conllueditor#20]
I get this error "docker: invalid reference format" with the recent Docker version 20.10.16, build aa7e414 running the following docker command (edit from the readMe):
```
sudo docker run --rm -t -d   --name conllueditor -p 8888:5555      --user 1000:1000        -v ~/Dokumente/conllu-editor-data:/data         --env filename=de_source.conllu      jheinecke/conllueditor:latest/
```
Do i have a typo or have the commands changed with the latest docker version?

**Comment by jheinecke** [comment]
I think the final slash in `jheinecke/conllueditor:latest/` causes the problem, try to use `jheinecke/conllueditor:latest`.

**Comment by Bachstelze** [comment]
Ok thanks, that is the problem.
