### ISSUE TITLE
Streamlining the installation

### ISSUE THREAD

**Issue by Stormur** [Orange-OpenSource/conllueditor#24]
Hi! 

The current way of installing of conllueditor seems to be a major hurdle for many users who are not so keen or practical on the more technical details, especially with regard to Windows. So I was wondering if it is possible to help this process a bit:

* giving links to the respective installation sites for jre, jdk, and maven;
* mentioning and giving links for the installation of node and npm (if I understand that they are needed; I had to install them);
    * specifying that jquery, bootstrap and popper can be installed with node, or
* making clearer that one might simply use the provided script `bin/installJQ.sh`  

I am further wondering if:

* a Windows-usable version of the script `bin/installJQ.sh` can be provided (I am not practical on this), so as to avoid roundabouts like Cygwin or WSL;
    * or, at least mention these latter possibilities 
* it is possible to just put all these installation/update routines into a kind of "exe-package"

I am reporting you that because in my experience this first step is the biggest, if not unsurmountable, problem for many users. 

Thank you for all your support!!!

**Comment by jheinecke** [comment]
Yes, I agree, there is room for improvement :-). I do not use Windows very often, but I could provide a compiled .jar file which avoids local compilation, and replacing the links to jquery etc to public sites (however when using public sites for jquery, the editor would not work without internet connection, so I'm not sure whether this is a good idea.
I'll have a look in making a installJQ.bat for windows users too.
However node and npm is not used :-)

**Comment by Stormur** [comment]
Darn, I thought it was needed and I installed it because it was the way I found to install the single java scripts before noticing the practical bash! :grimacing: 

The online constriction might be a viable compromise for some users.

**Comment by jheinecke** [comment]
Hi again,
I made a release in order to facilitate the installation. Everything needed is compiled and put into a simple zip-file. Should be straight forward for Linux, for Windows I'm not sure whether the command line works (cannot test it here). Please try and telle me what you think of it.

**Comment by Stormur** [comment]
Great as always, thanks!

We are launching some new annotations, so we will check this new method!

**Comment by Stormur** [comment]
OK, first note: it seems that the latest Windows version refuses to run and to modify the new `.cmd` file. Howver, if we create an equivalent `.bat`, it works without problems. 

Also, the validator file for Windows seems to require that python is called before `validator.py` (so something like `script: py <...>\validator.py ...`)

**Comment by jheinecke** [comment]
Hi created a new pre-release and changed the `ce.cmd` to `ce.bat` (and corrected some issues for Linux too. This replaces the first pre-release. I hope this servers you better

**Comment by Stormur** [comment]
I have been trying to run the editor on my old Windows (10) laptop, but it does not seem to work. I have updated java. 

I downloaded the `conllueditor-master` (is this the mentioned "`a.b.c.`"?) folder, unzipped it and just tried to launch it with 

` .\bin\conlluedit.sh --rootdir .\gui\ .\file.conllu 8888`

A terminal window opened briefly and then closed; the server is not reachable. 

Am I missing something?

**Comment by jheinecke** [comment]
Unless you have WSL or cygwin installed `bin\conlluedit.sh` will not work, since, to my knowledge, there is no bash interpreter on Windows. So in this case either use the ce.bat script or try to run 
```
java -jar conllueditor-2.16.2\target\ConlluEditor-2.16.2-jar-with-dependencies.jar --rootdir conllueditor-2.16.2/gui treebank.conllu 8888
```

**Comment by Stormur** [comment]
I have WSL, but maybe I have to install a specific Linux distribution. It seems that the Powershell can handle those sh, though. I'll try!

**Comment by Stormur** [comment]
Dear @jheinecke ,

I am trying to run conllueditor on another Windows machine, but we are not able to make it work. We are trying to run the `bat` file, but it outputs an error, apparently because the username in the string `C:\Users\USERNAME\...` contains a space.

So I have two main issues/questions:
* can we circumvent the user name problem just by changing the paths in the `bat` file?
* apart from this problem, should conllueditor be ready to be run just through the `bat` file or is there still something else to do?

**Comment by jheinecke** [comment]
Hi, I guess the easiest way is to start the server without the `.bat` script on a commandline using quotes
```
java -jar "C:\Users\USERNAME\...\ConlluEditor-2.21.1-jar-with-dependencies.jar" [options]  yourfile.conllu 5556
```
Do you try it on pure Windows or within a WSL? For the latter case the `bin/conlluedit.sh` should work, but obviously I didn't try with blanks in the path. You could try to modify `bin/conlluedit.sh` an put  quotes around `$NEWESTJAR` and `$ROOTDIR`:

```
java -Xmx4g -cp "$NEWESTJAR" com.orange.labs.editor.ConlluEditor "${ROOTDIR}" "$@"
```

**Comment by Stormur** [comment]
> Do you try it on pure Windows or within a WSL?

We are trying it on a "pure" Windows, I think (no WSL installed), from the Powershell.

**Comment by jheinecke** [comment]
did putting the variables within quotes help?

**Comment by Stormur** [comment]
Sorry, we'll have to retry as soon as possible, we were not able to go on yet. 

I will also try the "experiment" on a Windows device of mine (the same I mentioned in previous posts, on which it seems that I was not able to make conllueditor run).

I will let you know!

**Comment by Stormur** [comment]
OK, everything works smoothly but a couple of apparent bugs (new issue incoming)!

It was my bad that  I had not noticed that the latest release on the right of the page is not the same as the master repository, that is why I was confused about the jar! My suggestion thus could be to make it clearer for Windows user where the needed zip is :slightly_smiling_face: 

Thanks for all the support as always!
