### ISSUE TITLE
Mass Editor on Mac

### ISSUE THREAD

**Issue by ClaudiaCorbe** [Orange-OpenSource/conllueditor#29]
Hi, 

I got the following Error when trying to edit my conllu file using Conllueditor (I have a MacBook). I have already installed ConlluEditor and I can use it without any problems.

```
./bin/replace.sh ../../udpipe/puliziaXpos train6_pulito.conllu                
readlink: illegal option -- f
usage: readlink [-n] [file ...]
usage: dirname path
ls: /../target/ConlluEditor-*: No such file or directory
Unrecognized option: --conll
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Comment by jheinecke** [comment]
Hi
looks like that `uname -s` does not return `Darwin` anymore. I do not have access do a Mac, but could you run `uname -s` and tell me what this command says? If it is something different than `Darwin`, you could simply modify line 9 in `bin/conlluedit.sh` and change `Darwin` to the new value (I will updated it here.)
On macs I think `greadlink` must be installed (`brew install coreutils`)

**Comment by ClaudiaCorbe** [comment]
Hi,

I ran `uname -s` and the output was `Darwin`. 
I launched `brew install coreutils` but I got the same problem.

**Comment by jheinecke** [comment]
found the problem, the `uname -s` call was missing in `bin/replace.sh`. Looks like you are the first Mac user using `replace.sh` :-)
I pushed it to the repository so a `git pull` should correct it on your side. Or use the 2.21.1 release

**Comment by ClaudiaCorbe** [comment]
Now it works! Thank you very much! :)
