### ISSUE TITLE
Issue with readLink in conlluedit.sh on Mac

### ISSUE THREAD

**Issue by JPJPJPOPOP** [Orange-OpenSource/conllueditor#3]
Running `bin/conlluedit.sh -r treebank.conllu 8888` on macOS version 10.14.6 gives me the following error:
```
readlink: illegal option -- f
usage: readlink [-n] [file ...]
usage: dirname path
ls: /../target/ConlluEditor-*: No such file or directory
jar: 
Unrecognized option: --rootdir
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

I found [a fix](https://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac/4031502#4031502) for it by installing coreutils (`brew install coreutils`) and changing line 6 of `conlluedit.sh` to `BASENAME=$(dirname $(greadlink -f $0))`. It seems like readlink does not have the -f option on mac.

**Comment by jheinecke** [comment]
Thanks for this info. I did not realise that `readlink` does not have the option `-f` on Mac. `greadlink` on the other hand does not seem to be available on Linux. There is also `readpath` (on Linux), but once again I do not have access to a Mac for the time being, so could you confirm whether it is available on Mac?
