### ISSUE TITLE
Table view

### ISSUE THREAD

**Issue by Stormur** [Orange-OpenSource/conllueditor#36]
Hi!

With the table view, for annotation I see a problem in not being able to see all the FEATS/MISC features at once because of the field being too narrow. I would like to have at least the option to expand these (and any) fields as much as possible to get the whole picture. This is very helpful when e.g. one is not annotating for syntax.

Thank you!

**Comment by jheinecke** [comment]
Hi
I'll have a look. Should be possible

**Comment by Stormur** [comment]
Thanks!

Also, could it be possible to allow the shortcut modifications in table view, too? Thanks again!

**Comment by jheinecke** [comment]
I'll try that too.
for the widht of the cells in table view, I have a quick workaround (I'll try to make this modifiable from the UI, at least for the current session).
open gui/table.css and look for 
```
.ifeat { 
    width: 250px;
}
```
then set the width to any value you like and reload the page (F5 in firefox). This will enlarge it immediately.

**Comment by Stormur** [comment]
Thanks, for now it is working well!

**Comment by jheinecke** [comment]
checkout version 2.25. shortcuts work now (click on the Token id number (it becomes yellow) and than shortcuts work as in tree/hedge view. + and - can be used to see next/precedent sentence in table view as well now. And little =/- buttons on columns which might be very large (Feats, Deps, Misc) permit to enlarge or shorten the column width :-)

**Comment by Stormur** [comment]
Seems to work well!

Just two comments:

- is it possible to keep the chosen width also passing from sentence to sentence? 
- is it possible to have same treatment for all fields, actually? It happens that e.g. some lemmas are too long...

In the meantime, I think I have to open a new small issue! :-D

**Comment by jheinecke** [comment]
try V2.25.1 :-)

**Comment by Stormur** [comment]
Updated and using it! Everything seems fine at the moment, thanks again!
