### ISSUE TITLE
CoNLL-U plus, split & compose

### ISSUE THREAD

**Issue by Stormur** [Orange-OpenSource/conllueditor#37]
I have found a couple of small inconvenients when splitting/composing tokens in a text with more than the regular 10 UD columns.

1. When saving the file, additional columns of a newly composed MWT are left empty; this then gives an error when validating, or also when restarting conllueditor. The expected behaviour would be to put * there for "non-applicable" 
    2. Besides, it seems it is not possible to modify that value for a MWT, at least from a table view.
3. From a table view, it is not possible to modify the form of a MWT; I have to switch to the tree view

Thank you again!

**Comment by jheinecke** [comment]
Oh yes you're right. I'm on it. 
For the additional columns for MWT, I think I'll put `_` in the conllu-plus file. Since MWT's only have an id, a form and a MISC column, all other columns will be un-editable

**Comment by Stormur** [comment]
I just note that the standard value for a plus column is _*_, while _ means that it should be assigned one, but it was not. So the former should be preferred, I think.

**Comment by jheinecke** [comment]
I released a new version (2.25.3) which corrects all these issues

**Comment by Stormur** [comment]
Great! I am updating it!
