### ISSUE TITLE
Shortcuts and table view

### ISSUE THREAD

**Issue by Stormur** [Orange-OpenSource/conllueditor#38]
I am noticing this strange bug: in table view, when selecting a row and using a shortcut from the keyboard, not too infrequently the tag is assigned to another (random?) token. I wonder why this happens. 

And about shortcuts: 
* would it be possible to assign negative taggings, i.e. removal of features, both a specific one and all at once?
* it would be practical if the selected tokens remained selected for further tagging after using any shortcut. Now, if I want to tag different values, I have to reselect it each time.

Thank you as always! :pray:

**Comment by jheinecke** [comment]
To remove *all* features (FEAT) of a word, mark the word and type `_`. I'll see how I can keep the word marked for further shortcuts. Maybe a second way to mark (and and unmark) to keep the current way as it is.
I'll also check for the bug. Didn't observe it yet, but I'm more on tree view

**Comment by Stormur** [comment]
More about that bug: I have noticed that sometimes it gives me an "out of bound" error, for example trying to reach token 65 when there are only 50. It seems that somehow a count goes on behind the scenes, and often the obtained number corresponds to an existing token's id, so it applies the shortcut to it. I would say it happens at least 1 out of 10 times.

**Comment by jheinecke** [comment]
What does your  shortcut change: UPOS, UPOX+XPOS, FEAT or deprel ? I try to reproduce it, without success so fat

**Comment by Stormur** [comment]
I am using them for UPOS, features and miscellaneous. It seems to happen in each case.



> To remove _all_ features (FEAT) of a word, mark the word and type `_`.

Can this be implemented for `MISC`, too?

**Comment by jheinecke** [comment]
That exists already (but was missing in the documentation) `/` deletes all key=values from the MISC column.
I found the reason for the bug: There is a reinitialisation missing, so if you click on an ID and than choose a new sentence before issuing a shortcut, the ID clicked originally is used (and not the new one). I corrected this and push it ASAP

**Comment by jheinecke** [comment]
See version 2.25.3. Only thing missing is the *keep the word marked* feature. I'll have to think how to do it the best way. Eithe a checkbutton (which has to be active) or a Shift-Click on the word. What to you think is more practical?

**Comment by Stormur** [comment]
Since this works with shortcuts, I would prefer the keyboard option, so maybe shift!

**Comment by jheinecke** [comment]
It took a little while, but I've just pushed V2.25.4
In table view Ctrl-Click marks a word for short cut and it stays marked until you change the sentence or click another word
