### ISSUE TITLE
Spaces in installation directory name

### ISSUE THREAD

**Issue by jerekupari** [Orange-OpenSource/conllueditor#39]
I just tried to extract ConlluEditor to `C:\Program Files`. 

Starting the server with this command results in an error.
`java -jar 'C:\Program Files\conllueditor-2.25.3\target\ConlluEditor-2.25.3-jar-with-dependencies.jar' --rootdir 'C:\Program Files\conllueditor-2.25.3\gui\' MM-la_perseus-ud-test.conllu 8888`
```
usage: ConlluEditor [options] CoNLL-U-file port
missing CoNLL-U-filename and/or port number
```
(Also tried using double quotes " with same result.)

From `C:\ProgramData` it works perfectly, with or without quotes. I guess this is because of the space in 'Program Files'. It's not a big deal but maybe it could be mentioned in the installation instructions.

I saw you discussing spaces in directory name previously: https://github.com/Orange-OpenSource/conllueditor/issues/24#issuecomment-1553093669 . But @Stormur did not explicitly tell if they got it working with a space in the name.

(Edit: Windows 10 Home, PowerShell)

**Comment by jheinecke** [comment]
spaces in the path are in issue if you use `bin/conlluedit.sh`. I'll have a look whether I find a solution. 
It looks like you started the server directly using `java -jar ...` in the command line. I wonder whether the `...gui\'` is the problem. did you try `....\gui` without the final backslash.

**Comment by jerekupari** [comment]
Ooh! Without the backslash after gui it works.

Thanks!
