### ISSUE TITLE
Error reading sentence

### ISSUE THREAD

**Issue by david-kuehn** [Orange-OpenSource/conllueditor#40]
Hello,

I'm running into an error when pressing "Read Sentence" that I haven't been able to get past. I am using the latest version and JDK v18. The error is below:

"General error: Cannot invoke "String.length()" because the return value of "com.orange.labs.conllparser.ConllSentence.getText()" is null"

It appears that the CONLL-U file is being successfully loaded, because I am able to see the statistics when I click on the filename in the editor, but if I try to press any of the buttons below, I get the error.

**Comment by jerekupari** [comment]
I get the same error if there is no `# text =` line at the beginning of the sentence.

**Comment by david-kuehn** [comment]
I was able to get this issue resolved by revising the formatting of the CONLL-U file that I was trying to load.

**Comment by jerekupari** [comment]
Great.

I noticed that Trankit does not write the `# text = ...` line when using the `trankit2conllu()` function.
https://github.com/nlp-uoregon/trankit/issues/85

It would be nice if ConlluEditor would be able to load the file nevertheless, maybe with the --relax switch. Looking at the GUI I don't see why the `# text` would be necessary, but of course that doesn't mean it is easy to do.

**Comment by jheinecke** [comment]
I'll have a look at that.

**Comment by jheinecke** [comment]
It's done: get V2.25.5!

You surprised me in a good moment :-)

**Comment by jerekupari** [comment]
It works! Thanks :)
