### ISSUE TITLE
More verbose error messages?

### ISSUE THREAD

**Issue by AngledLuffa** [Orange-OpenSource/conllueditor#41]
I ran into an error with the following line:

```
Loading /afs/cs.stanford.edu/u/horatio/UD_Sindhi-Isra/not-to-release/xpos/xpos_tagged_with_features.conllu
*** Error: invalid line: 401 '1 چيومانو چيومانو VERB    VMX     Aspect=Perf|Number[Subj]=Sg|Person[Subj]=1|Number[Obj]=Pl|Person[Obj]=2  0      root    _      _' (line 406)
```

It may not be clear from the output, but this line had a space and not a tab between two of the columns.  A message that the line was invalid for only having 9 tab separated columns would be quite helpful here

**Comment by jheinecke** [comment]
Good point ! thanks ! I'll try to make the error message more specific

**Comment by jheinecke** [comment]
I've just pushed version which gives more specific error messages when loading a file.

**Comment by AngledLuffa** [comment]
Excellent, thank you!
