### ISSUE TITLE
Features smart dialog?

### ISSUE THREAD

**Issue by AngledLuffa** [Orange-OpenSource/conllueditor#42]
Am wondering - in the table view, the features editing appears to be done by manually adjusting the features.  Is there a possibility of an interactive dialog where the features are separated into their different items and candidate values are proposed?  I'm thinking somewhere where the raw features for a verb start off like this:

```
Gend=Masc|Number=Sg|Tense=Present
```

and clicking on it would give a sequence of radio buttons:

```
Gend =  X  Masc   O Fem
Number =    X Sg    O Plur
Tense = O Past   X Present   O Future
```

maybe with None as an option to indicate that feature isn't present for that word

Mostly I'm looking for ways to make the web interface as easy to use for non-technical people as possible

**Comment by jheinecke** [comment]
I'll have a look into that. Should be feasible when the valid values for features per UPOS are known

**Comment by jheinecke** [comment]
I'm working on that, but I'm stuck with the problem that the official documentation which features can go with which UPOS is not (yet) usable (see https://github.com/UniversalDependencies/docs/issues/1055). I think a local configuration file will be necessary until data/feats.json is cleaned up. What languages are you currently editing ? Could you provide me with a list for each language with `UPOS <TAB>Feature=Value ...` like
```
NOUN	Gender=Fem Gender=Masc Number=Dual Number=Plur Number=Sing
VERB	Tense=Past ....
```

**Comment by jheinecke** [comment]
I added a smart feature selection scheme in table view mode. You need to use the `feats.json` file from the UD-tools repository. Possibly the information for your language is erroneous in this file, than you need to create a new one based on your data (see [README.md)](README.md) or modify the one from UD.

**Comment by AngledLuffa** [comment]
Thanks for looking into this!  I am currently on vacation (which is why I
haven't written back sooner about the features table) but I will give it a
try this week anyway.

**Comment by AngledLuffa** [comment]
Thanks for taking care of this!  I realized I had neglected to respond to the new form.  It looks quite nice.

It look like it allows for features incompatible with the UPOS - I believe the feats.json file has the information on which upos can support which features.   Such as for example this random line from the English file:

```
"Degree": {"type": "universal", "doc": "local", "permitted": 1, "errors": [], "uvalues": ["Cmp", "Pos", "Sup"], "lvalues": [], "unused_uvalues": [], "unused_lvalues": [], "evalues": [], "byupos": {"ADJ": {"Cmp": 1, "Pos": 1, "Sup": 1}, "ADV": {"Cmp": 1, "Pos": 1, "Sup": 1}, "DET": {}, "INTJ": {}, "NOUN": {}, "PRON": {}, "PROPN": {}, "PUNCT": {}, "SCONJ": {}, "VERB": {}, "X": {}}, "lastchanged": "2024-09-26-01-49-52", "lastchanger": "nschneid"},
```

Still, it's really quite an improvement over having to type in the features by hand
