### ISSUE TITLE
tree modification causing slowdown

### ISSUE THREAD

**Issue by ClaudiaCorbe** [Orange-OpenSource/conllueditor#43]
Hello,

I am encountering an issue with the tool when using the interface to move from one sentence to another after making modifications to the trees.
After completing changes to a tree and pressing the arrow to move to the next sentence, the following screen appears, and the program freezes:

![Schermata 2024-09-24 alle 14 54 05](https://github.com/user-attachments/assets/a7ba0341-86d9-4de7-8180-a51ac89aca54)

I have to wait about a minute, repeat the action twice, and only then can I successfully proceed to the next sentence.
Could you advise me on how to resolve this issue? When no modifications are made to the trees, I can navigate through them without any problems. The slowdown (and the message on the screen) occurs only when changes are made.

I am using a Mac and typically work with Safari, but I have also tried using Google Chrome, and the slowdown persists.

Best regards,
Claudia

**Comment by jheinecke** [comment]
Hi,
that looks as if there is a problem in writing the edited sentence into the file. Is there any output in the terminal where you started the server ?

**Comment by ClaudiaCorbe** [comment]
The terminal output is: 

```
2024/09/24 15:48:52 POST EditHandler request from localhost/[0:0:0:0:0:0:0:1]:60463
COMMAND [mod 2 3 ] sid: 9
2024/09/24 15:48:54 POST EditHandler request from localhost/[0:0:0:0:0:0:0:1]:60463
COMMAND [next] sid: 9
File '/Users/claudia/path/file.conllu' not tracked by git
2024/09/24 15:50:11 POST EditHandler request from /[0:0:0:0:0:0:0:1]:60476
COMMAND [next] sid: 9
2024/09/24 15:50:11 POST EditHandler request from /[0:0:0:0:0:0:0:1]:60478
COMMAND [next] sid: 9
2024/09/24 15:50:11 POST EditHandler request from /[0:0:0:0:0:0:0:1]:60481
COMMAND [next] sid: 9
```
as you can see, it takes around two minutes to process the command.

**Comment by ClaudiaCorbe** [comment]
I moved the file I'm working on to the same folder as the program, and the process has sped up, with no more warnings appearing. Problem solved! I’ll keep everything in this folder—no more jumping around.

**Comment by jheinecke** [comment]
How did you install ConlluEditor? `git clone` or did you use the package ? If it is `git clone` than the problem may be linked to git. Apparently the path where you had your file initially  is not under git version control, so something caused CE on MAC slows it down (I'll have to check, but I do not have access to a MAC...). Now you have moved it to the directory where ConlluEditor resides and this is under git control. Strange however.

**Comment by ClaudiaCorbe** [comment]
Yes, I used `git clone`. 
I will keep everything in the folder to avoid any slowdown. 
Thank you for your prompt response.

**Comment by jheinecke** [comment]
the delay of 2mins should not be there if the file is not under git control. Is there anywere in `/Users`, `/Users/claudia` or `/Users/claudia/path/` a `.git/` directory ?

**Comment by ClaudiaCorbe** [comment]
I realized that the file was mistakenly inside a `.git/` directory. I made some modifications, and now it works properly even if the file is in other folders.

**Comment by jheinecke** [comment]
OK, that was probably the cause. Not sure whether I can do for this in the editor :-)
