### ISSUE TITLE
Grewmatch dependencies

### ISSUE THREAD

**Issue by Stormur** [Orange-OpenSource/conllueditor#44]
Hi!

Either after pulling or cloning the folder anew, I get an error trying to use `mvn install`. In particular, these lines:

```
 Compilation failure
[ERROR] /home/stormur/Documenten/UD/conllueditor/src/main/java/com/orange/labs/conllparser/ValidFeatures.java:[35,24] package GrewmatchVisitor does not exist
```

What about GrewmatchVisitor?!

**Comment by jheinecke** [comment]
I'll have a look, I could reproduce it....

**Comment by jheinecke** [comment]
I have just pushed a corrected version. I deleted the unneeded import GrewmatchVisitor (no idea how this got in there and why my tests didn't spot it.

**Comment by Stormur** [comment]
Perfect, now everything is fine again! Thanks!
