### ISSUE TITLE
Relations in downloaded figures

### ISSUE THREAD

**Issue by megasser** [Orange-OpenSource/conllueditor#45]
[New group of users here (Amharic and Tigrinya treebanks).]
We noticed the relation labels are missing in the downloaded SVG images (both flat and tree displays). Would it be possible to add those?

**Comment by ioan2** [comment]
Did you try to visualize the donwloaded svg file with inkscape  or inkview? I observed that the Ubuntu (22.04) image viewer (eog) is not able to display text which is not horizontal (svg textPath). Libreoffice Draw also displays the textPaths (but does not turn the letters correctly. Could you post me a sentence from you file to check?

**Comment by megasser** [comment]
I was viewing (and exporting) the file in GIMP. But I tried Inkscape, as you suggested, and I now see the relation labels (in the SVG file and the exported PNG file). Thank you for your help!
