### ISSUE TITLE
Installation complications

### ISSUE THREAD

**Issue by Stormur** [Orange-OpenSource/conllueditor#46]
Hi!

I am trying to install conllueditor on Windows systems, by means of the latest precompiled release. One problem that I encounter is that Java is needed, but apparently not present by default on all systems. And installing what is found online (Java 8) is not good: I obtain the error that the release uses runtime 55 instead of the detected 52 (I cannot replicate this error right now, unfortunately). 

So my question is: is it possible to put a warning and a clear reference to the needed version of Java in the README? This would be really helpful.

Thank you!

**Comment by jheinecke** [comment]
Hi, 
good point, It's said in the general README but not in the release. I'll add this! Thanks

**Comment by Stormur** [comment]
Thanks! It can be really confusing for many who are not so familiar with all these trappings. A link in the README would be the most helpful thing. 

Ad maiora!
