### ISSUE TITLE
Download image

### ISSUE THREAD

**Issue by Stormur** [Orange-OpenSource/conllueditor#5]
When I download an image, be it in tree or flat format, the names of dependency relations are not shown in the svg file.

**Comment by jheinecke** [comment]
This is a strange thing. The deprels are in fact in the downloaded `.svg` file but `eog` (for instance) does not show them). `inkscape` and `inkview` do show them, as does ImageMagick's `display` (all on Linux). Which tool do you use to visualize the `.svg` file?

**Comment by Stormur** [comment]
I am using the standard image viewer of Ubuntu 18.04, codename bionic!

**Comment by jheinecke** [comment]
Yes, that's the tool I called `eog`. I do not know yet why it does not show the deprels. Did you try `inkview`?

**Comment by Stormur** [comment]
I installed Inkscape and yes, with it the deprels are shown.

**Comment by jheinecke** [comment]
I do not know whether the Ubuntu image viewer is buggy. I checked the svg with a validator and it did not report any error.
