### ISSUE TITLE
Splitting and joining sentences

### ISSUE THREAD

**Issue by Stormur** [Orange-OpenSource/conllueditor#6]
I noticed two quirky behaviours:

* when the command sentsplit is given, the sentence is correctly split, but the text in the metadata is not split correspondingly, so that validation raises an error;
* the sentence which is joined by the command sentjoin (the "rightmost one" for a left-to-right script) has all the nodes reattached as roots.

**Comment by jheinecke** [comment]
The first issue is fixed (commit 92cd116). Joining two sentences do not add/delete any dependency relations, So after joining you still have to add relations to have a single dependency tree.
