### ISSUE TITLE
Managing multitoken words

### ISSUE THREAD

**Issue by Stormur** [Orange-OpenSource/conllueditor#7]
I noticed some quirky behaviour when joining or splitting tokens:

* When creating the tag for a multitoken word, I am not able to change it in any way, for example by clicking on the grey bar, as stated in the _help_ section;
* if I want to delete a multitoken word, something strange seems to happen in the CoNLL-U: 
    * in the interface, it still remains a short grey bar with the former tag upside-down;
    * in the CoNLL-U, there is a decreasing range, like e.g. `4-3 del _ ...`;
    * some of the involved CoNLL-U lines look like being "compressed", with some tabulations missing between the fields. This also had the effect that the interface could not show me the sentence anymore once I changed to another: the arrow simply didn't work anymore from either direction.

Thanks for the attention! :-)

**Comment by jheinecke** [comment]
I think the grey bar is to small... I missed it too. If you hit it :-) the MWT editor should open. Could you give me the sentence which caused the error when you deleted the MWT? How did you delete it?
I'll will fix that.

**Comment by Stormur** [comment]
Hm, unfortunately I changed some things, but after recomposing the CoNLL-U with `compose 4 0` it looks like:

1	Il	_	DET	_	_	2	det	_	_
2	gatto	_	NOUN	_	_	3	nsubj	_	_
3	cade	_	VERB	_	_	0	root	_	_
4-3	da	_	_	_	_	_	_	_	_
4	da	_	ADP	_	_	6	case	_	_
5	il	_	DET	_	_	6	det	_	_
6	tetto	_	NOUN	_	_	3	obl:arg	_	SpaceAfter=No
7	.	.	PUNCT	_	_	3	punct	_	_

![Schermata del 2020-05-20 17-33-23](https://user-images.githubusercontent.com/32514840/82465863-09616e80-9ac0-11ea-8e47-6b720061533d.png)

But at the moment I can't manage to replicate that error... however, I did successive splittings and joinings.

And I managed to hit the grey bar! :-)

**Comment by jheinecke** [comment]
Thanks, I'll try to reproduce by doing evil annotations :-)

**Comment by jheinecke** [comment]
fixed in commit 92cd116
